### PR TITLE
Add py3.10 test configuration

### PR DESCRIPTION
**Pull request by kanderso-nrel**
Now that python 3.10 has been out for a little while and the core pydata packages have released wheels, I figure it's time to start testing on it :)

### CODE REVIEW

**Comment by kanderso-nrel** [comment]
Hmm, the failure is in the docs build -- seems that the napoleon sphinx extension is not yet compatible with python 3.10: https://github.com/sphinx-contrib/napoleon/issues/9

So I suppose this PR is on ice until that is addressed.

**Comment by kanderso-nrel** [comment]
Silly me -- I didn't realize there was a difference between the external napoleon extension linked above and the one built into sphinx itself.  I've switched to the built-in version in d8e24bb and everything seems to be working.  This PR is now "off ice" and ready for review.

**Review by anomam — APPROVED** [review]
Thanks @kanderso-nrel ! LGTM

**Comment by kanderso-nrel** [comment]
@campanelli-sunpower here's a ping in case you're not watching this repository :)

**Comment by campanelli-sunpower** [comment]
@kanderso-nrel Thanks for updating this. Unfortunately I missed this PR before I jumped on the v1.5.2 release earlier today. Would you kindly update this PR for the next release (likely v1.5.3)?

**Comment by kanderso-nrel** [comment]
Sure thing, updated :)

**Pull request merged**
